@Library('olcne-pipeline')
import com.oracle.olcne.pipeline.BranchPattern

String version = "4.13.2"
String imageTag = "v" + version
String container_registry_namespace = "olcne"
String registry = "container-registry.oracle.com/" + container_registry_namespace

imagePipeline(
        branchPattern: new BranchPattern(master: 'oracle/release/.*', feature: '(?!^release/.*$)(^.*$)'),
        containers: [(registry + '/nfsplugin:' + imageTag) : container_registry_namespace + '/nfsplugin:' + imageTag],
        architectures: ['x86_64', 'aarch64'],
        platforms: ['ol9'],
        buildScript: "sh olm/build-image.sh"
)
